### PR TITLE
Update bundle application to use latest edge on jammy

### PR DESCRIPTION
**Pull request by welpaolo**

### CODE REVIEW

**Review by marcoppenheimer — APPROVED** [review]

**Review by deusebio — APPROVED** [review]
Hurray!!!!!!

**Comment by deusebio** [comment]
Before merging can we just double check that the error message we get in integration tests are something we should not worry about?

@marcoppenheimer @welpaolo

**Comment by marcoppenheimer** [comment]
@deusebio - They're fine. When we defer a relation event because of one or both applications not having TLS, it emits an error and defers. The test passes because it resolves, so we're OK.

**Comment by deusebio** [comment]
Cool! Thanks for the check!

**Review by deusebio — APPROVED** [review]

**Pull request merged**
